### ISSUE TITLE
Key length error in impl.ts 

### ISSUE THREAD

**Issue by plouis01** [massalabs/massa-sc-library#33]
While runing the function _balance and _setBalance of massa-sc-library/token/assembly/std/impl.ts, we get :

`Runtime error: bytecode execution error: RuntimeError: RuntimeError: Runtime error: key length is 51, but it must be in [0..32]`

and while runing the function _allowance, _approve, we get :

`Runtime error: bytecode execution error: RuntimeError: RuntimeError: Runtime error: key length is 103, but it must be in [0..32]`

This is due to the fact that `Storage.setItem(<key>, <args>)` and  `Storage.getItem(<key>, <args>)` can only take a 33-character long key, thus not an address nor a concatenation of addresses as a key.

**Comment by damip** [comment]
Thanks for detecting this !
We will act on repairing it quickly. A simple first mitigation will be making the key length longer
